config/routes.rb
  Rails.application.routes.draw do

  # namespace :admin do
  #   resources :users
  #   root to: "devise/sessions#new"
  # end

  # root to: 'vendors#index'

  # devise_for :users
  # devise_scope :users do
  #   get '/', to: "devise/sessions#new"
  # end
  # root to: "sessions#index"


  devise_for :users, :controllers => { registrations: 'registrations' }
  authenticated :user do
    root to: 'vendors#index'
  end

  root to: "sessions#index"

  get '/super_admin_delete', to: 'users#super_admin_delete'

  get '/forum', to: 'posts#forum'
  get '/documents/:id/download', to: 'documents#download', as: :download

  resources :users

  resources :documents, only: [:new, :create, :index, :show, :destroy]

  resources :roles, only: [:new, :create]
  post '/admin', to: 'roles#admin'
  post '/member', to: 'roles#member'

  resources :posts, only: [:new, :create, :edit, :update, :destroy]

  resources :privacy, only: [:edit, :update]

  resources :organisations, only: [:new, :create, :edit, :update]

  resources :password_resets

  resources :vendors do
    resources :reviews, except: :index
    resources :offerings
  end

  # resources :reviews do
  #   resources :votes
  # end

  resources :categories, only: [:index, :show, :new, :create]

  get 'locations/all', to: 'locations#all'
  resources :locations, only: [:index, :show, :all, :new, :create, :edit, :update]

  namespace :admin do
    resources :vendors
    resources :users do
      resources :roles
    end
  end

  get '/data', to: 'categories#data'

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  belongs_to :organisation
  has_many :reviews
  has_many :votes
  has_one :privacy
  has_and_belongs_to_many :roles
  has_many :documents
  has_many :posts

#  has_secure_password

  validates :email, uniqueness: true
  validates :email, presence: true
  validates :first_name, :last_name, presence: true
  validates :organisation_id, presence: true
  validates_format_of :email,:with => /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/
  # validates_associated :organisation
  validates_associated :roles

  def full_name
  	self.first_name + " " + self.last_name
  end

  def add_role(role_id)
    role = Role.find(role_id)
    self.roles << role
  end

  def is_admin?
    admin = Role.find_by name: 'Admin'
    self.roles.include? admin
  end

  def ambassador?
    ambassador = Role.find_by name: 'Ambassador'
    self.roles.include? ambassador
  end

  def member?
    member = Role.find_by name: 'Member'
    self.roles.include? member
  end

  def pending?
    self.roles.length == 0
  end

  def date_format(expiration_date)
  	expiration_date.strftime("%m/%d/%y")
  end

  def location
    Location.find_by organisation_id: self.organisation.id
  end

  def send_password_reset
    generate_token(:password_reset_token)
    self.password_reset_sent_at = Time.now
    self.save!

    #UserMailer.password_reset(self).deliver
  end

  def generate_token(column)
    while User.exists?(column => self[column])
      self[column] = SecureRandom.urlsafe_base64
    end
  end



end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  include ApplicationHelper
  before_action :require_admin

  def index
    @user = current_user
    @users = User.order(:last_name)
    @memberrole_id = Role.find_by(name: 'Member').id
    @adminrole_id = Role.find_by(name: 'Admin').id
  end

  def require_admin
    unless admin?
      flash[:alert] = "Please log in with admin credentials"
      redirect_to root_path
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

before_action :authenticate_user!, except: [ :new, :create ]

  def index
    if admin?
      @organisations = Organisation.order(:name)
    else
      flash[:access] = "Unauthorized access, please log in."
      redirect_to '/'
    end
  end

  def show
    @user = User.find(params[:id])
    @reviews = @user.reviews.limit(5)
    @expiration = @user.date_format(@user.membership_expiration)
    @privacy = @user.privacy
    @ambassador = @user.ambassador?
    @roles = Role.new
  end

  def super_admin_delete
    @super_admin_emails = ['felipe@cpa.coop', 'lauren@cpa.coop', 'pauledwardmitchell@gmail.com']
    if @super_admin_emails.include? current_user.email
      @active_users = User.all.where.not(status: 'inactive')
      @inactive_users = User.all.where(status: 'inactive')
      @users = User.all
      @user_hashes = []

      @active_users.each do |user|
        user_hash = {
          user_id: user.id,
          user_name: user.full_name,
          user_status: user.status,
          user_organisation: user.organisation.name || nil
        }
        @user_hashes << user_hash
      end

      @data = {
        user_hashes: @user_hashes
      }
    else
      redirect_to current_user
    end

  end

  def edit
  	@user = User.find(params[:id])
  	unless @user.id == current_user.id
			flash[:access] = "Unauthorized access, please contact an administrator if you believe this error is incorrect."
      redirect_back
		end
  end

  def update
  	@user = User.find(params[:id])
    if @user.update(user_params)
	  	redirect_to @user
    else
      flash[:access] = "Unauthorized access, please contact an administrator if you believe this error is incorrect."
      redirect_to @user
    end
  end

  def new
    @user = User.new
    @organisations = Organisation.order(:name)
  end

  def create
    @user = User.new(user_params)
    # @organisation = Organisation.find(params[:user][:organisation_id])
    # if @organisation
    #   @user.organisation_id = @organisation.id
    # else
    #   @organisation = Organisation.create(name: params[:organisation])
    #   @user.organisation_id = @organisation.id
    # end
    if @user.save
      Privacy.create(user_id: @user.id)

      @role = Role.find_by(name: "Member")
      @user.add_role(@role.id)
      #UserMailer.membership(@user).deliver_now

      redirect_to root_path
      flash[:new] = "Welcome to MARVL!"
    else
      @errors = @user.errors.full_messages
      @organisations = Organisation.order(:name)
      render "new"
    end
  end

  # def patch
  #   @user = User.find(current_user.id)
  #   if @user.update(user_params)
  #     redirect_to root_path
  #   else
  #     render "edit_password"
  #   end
  # end

  private
  def user_params
    params.require(:user).permit!
  end
end

app/views/users/ambassadors.html.erb
<h1>Membership Ambassadors</h1>
<p>Our membership ambassadors are happy to answer any questions you might have about CPA</p>

<% @ambassadors.each do |ambassador| %>
	<% ambassador.users.each do |user| %>
		<%= user.full_name %><br>
		<%= user.organisation.name %><br>
		<%= user.email %><br><br>
	<% end %>
<% end %>

app/views/users/edit.html.erb
<center><h1>Edit your Information</h1></center>

<%= form_for @user, :html => {:class => "form-group"}, :url => {:action => 'update', :id => @user.id} do |f| %>
  <%= f.label :title %>:
  <%= f.text_field :title %><br>
  <%= f.label :first_name %>:
  <%= f.text_field :first_name %><br>
  <%= f.label :last_name %>:
  <%= f.text_field :last_name %><br>
  <%= f.label :email %>:
  <%= f.text_field :email %><br>
  <%= f.submit "Update" %>
<% end %>

app/views/users/edit_password.html.erb
<h2>Change Password</h2>

<div>
  <%= form_tag patchpassword_path, method: 'post' do %>
    <div>
      <%= label_tag(:old_password, "Type old password") %><br>
      <%= password_field_tag (:old_password)  %>
    </div><br>
    <div>
      <%= label_tag ("Type new password") %><br>
      <%= password_field_tag (:new_password_1)  %>
    </div>
    <div>
      <%= label_tag ("Confirm new password") %><br>
      <%= password_field_tag (:new_password_2) %>
    </div>
    <div>
      <%= submit_tag %>
    </div>
  <% end %>
</div>

app/views/users/index.html.erb
<h1>CPA Member Institutions</h1>

<%# link_to "See our Members on an Interactive Map", locations_path %>

<% if admin? %>
  <center>
    <h4>Can't find an Organisation that should be here? <%= link_to 'Add it now!', new_organisation_path %> </h4>
  </center>
<% end %>

<% @organisations.each do |organisation| %>
  <h3><%= organisation.name %></h3>

  <% if organisation.locations.length == 0 %>

    <%= link_to "Add location info", new_location_path(org: organisation.id) %>
  <% else %>
    <% organisation.locations.each do |location| %>
      <%= location.name %> | <%= location.phone %><br>
      <%= location.full_address %>
      <% if admin? || current_user.organisation.id == location.organisation.id %><br>
        <%= link_to "Edit this information", edit_location_path(location) %>
      <% end %>
    <% end %>
  <% end %>

  <% if organisation.active_users.length > 0 %>
    <ul>
    	<% organisation.active_users.each do |user| %>
        <li>Representative: <%= link_to user.full_name, user %></li>
      <% end %>
    </ul>
  <% end %>
<% end %>

<center>
<br>

<% if admin? %>
  <h4>Can't find an Organisation that should be here? <%= link_to 'Add it now!', new_organisation_path %> </h4>
<% end %>

</center>

app/views/users/new.html.erb
<center>
  <h1>Request Member Access</h1>
  <p>Building community knowledge is only moments away...</p>
</center>

<div class="alert">
<% if @errors %>
	<% @errors.each do |error| %>
		<%= error %>
	<% end %>
<% end %>
</div>

<%= form_for @user, html: {class: "form-group"} do |f| %>
	<%= f.label :title %>
  <%= f.text_field :title %><br>
  <%= f.label :first_name %>
  <%= f.text_field :first_name %><br>
  <%= f.label :last_name %>
  <%= f.text_field :last_name %><br>
  <%= f.label :email %>
  <%= f.text_field :email %><br>

  <%= f.label :organisation %><br><span> (If your organization is not listed, please choose <strong>*New CPA Partner*</strong>.)</span>
  <%= f.select(:organisation_id) do %>
    <%= content_tag(:option, 'Choose an Organisation', {value: nil, selected: "selected", disabled: true}) %>
    <% @organisations.each do |c| -%>
      <%= content_tag(:option, c.name, value: c.id) %>
    <% end %>
  <% end %>  

  <%= f.label :password %>
  <%= f.password_field :password, class: 'form-group password'%><br>
  <%= f.submit "Submit" %>
<% end %>

app/views/users/privacy.html.erb
<h1>Manage your Privacy Settings</h1>

<%= form_for @privacy, :html => {:class => "form-group"}, :url => {:action => 'update', :user_id => @user.id} do |f| %>
  <%= f.label :Email %>:
  <%= f.radio_button :email_allowed, 'show', :checked => true  %>
  <%= f.radio_button :email_allowed, 'hide', :checked =>false  %><br>
  <%= f.label :Organization %>:
	<%= f.radio_button :organisation_allowed, 'show', :checked => true  %>
  <%= f.radio_button :organisation_allowed, 'hide', :checked =>false  %><br>
  <%= f.label :membership_expiration %>:
  <%= f.radio_button :membership_allowed, 'show', :checked => true  %>
  <%= f.radio_button :membership_allowed, 'hide', :checked =>false  %><br>
  <%= f.submit %>
<% end %>

app/views/users/samplevendors.html.erb
<h1>Sample Vendors</h1>
<p>Upon joining CPA, you will receive access to a full list of vendors with user reviews</p>

<% @vendors.each do |vendor| %>
	<%= vendor.name %><br>
	<%# vendor.full_address %><br><br>
<% end %>

app/views/users/show.html.erb
<%# /users/:id/show %>
<div class="user-info">
  <%# if viewing user is admin %>
  <% if current_user.is_admin? %>

    <div class="admin-tools right">
      <h5> Admin Tools </h5>
      <ul>
        <li><%= link_to "View/Manage Users", admin_users_path %>
        <%# link_to "View Uploaded Documents", documents_path %>
        <li><%= link_to "Add Organization", new_organisation_path %>
        <li><%= link_to "Add Service Category", new_category_path %>

        <% if ['felipe@cpa.coop', 'lauren@cpa.coop', 'pauledwardmitchell@gmail.com'].include? current_user.email %>
          <li> <%= link_to "Deactivate a User", super_admin_delete_path %></li>
        <% end %>

      </ul>
    </div>
	<% end %>


  <h1><%= @user.full_name %> </h1>

  <% if @ambassador %> <h3> Membership Ambassador </h3> <%end%>

  <% if @user.is_admin?%> <h3> Admin </h3> <%end%>


	<% if admin? %>
    <%# viewing admin can promote non-admin viewed user to admin %>
    <% unless @user.is_admin? %>
      <%= form_for @roles, url: url_for(controller: "roles", action: "admin" ) do |f| %>
      <%= hidden_field_tag "user_id", @user.id %>
      <%= f.submit "Make #{@user.full_name} Admin" %>
      <% end %>
    <% end %>

    <%# viewing admin can approve pending user's membership %>
    <% unless @user.member? || @user.is_admin? %>
    <p><%=@user.full_name%>'s membership is currently pending</p>
      <%= form_for @roles, url: url_for(controller: "roles", action: "member") do |f| %>
      <%= hidden_field_tag "user_id", @user.id %>
      <%= f.submit "Approve Membership" %>
      <% end %>
    <% end %>

  <% end %>



  <%# links for admin and members seeing own page %>
  <% if @user.id == current_user.id %>
    <%= link_to "Edit Your Profile", edit_user_path(@user) %>  |
    <%= link_to "Privacy Settings", edit_privacy_path(@user) %> |
    <%= link_to "Change your password", edit_user_registration_path %>
  <% end %>

  <%# link to make oneself ambassador %>
  <%# if !@ambassador && @user.id == current_user.id %>
     <%# link_to "Become an Ambassador", new_role_path %>
  <%# end %>

<div class="user-profile user-info">

  <% if @privacy.membership_allowed %>
    <p>
      Membership Expiration:
      <span class="info-value">
        <%= @expiration %>
      </span>
    </p>
  <% end %>

  <% if @privacy.organisation_allowed %>
    <p>
      Organization:
      <span class="info-value">
        <% if @user.organisation.locations %>
          <%= @user.organisation.name %>
        <% end %>
      </span>
    </p>
  <% end %>

  <% if @privacy.email_allowed %>
    <p>
      Email:
      <span class="info-value">
        <%= @user.email %>
      </span>
    </p>
  <% end %>
</div>


<div class="user-profile recent-reviews-container">
  <h4>Recent Reviews by <%= @user.first_name %> </h4>
  <div class="recent-reviews-inner">
    <% if @privacy.reviews_allowed %>
      <% if @reviews.length > 0 %>
        <div class = "review">
          <%= render "shared/list_reviews_user_show", locals: { reviews: @reviews, vote: @vote} %>
        </div>
      <% else %>
        <div class="no-reviews">
          <p>
            No reviews yet!
          </p>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/users/super_admin_delete.html.erb
<%= react_component 'DeactivateUsersPanel', {data: @data}, authenticity_token: form_authenticity_token %>


<h2>Inactive Users</h2>

<% @inactive_users.each do |user| %>

  <% if user.first_name != nil && user.last_name != nil %>

    <h5><%= user.full_name %> | <%= user.id %> </h5>

  <% else %>

    <p>BAD NAME DATA</p>

  <% end %>

  <%= form_for [user] do |f| %>
    <%= f.hidden_field :status, :value => 'active' %>
    <%= f.submit "Make user active" %>
  <% end %>

<% end %>

<h1>All reviews</h1>

<table style="width:100%">
  <tr>
    <th>Organization</th>
    <th>Name</th>
    <th>Email</th>
    <th>Vendor Name</th>
    <th>Review</th>
    <th>Rating</th>
  </tr>

<% @users.each do |u| %>

    <% u.reviews.each do |r| %>

      <tr>
        <td><%= r.user.organisation.name %></td>
        <td><%= r.user.full_name %></td>
        <td><%= r.user.email %></td>
        <td><%= r.vendor.name %></td>
        <td><%= r.content %></td>
        <td><%= r.rating %></td>
      </tr>

    <% end %>
<% end %>

</table>

app/views/users/vendors.html.erb
<h1>Sample Vendors</h1>
<p>Upon joining CPA, you will receive access to a full list of vendors with user reviews</p>

<% @vendors.each do |vendor| %>
	<%= vendor.name %><br>
	<%= vendor.full_address %><br><br>
<% end %>