config/routes.rb
  Rails.application.routes.draw do

  # namespace :admin do
  #   resources :users
  #   root to: "devise/sessions#new"
  # end

  # root to: 'vendors#index'

  # devise_for :users
  # devise_scope :users do
  #   get '/', to: "devise/sessions#new"
  # end
  # root to: "sessions#index"


  devise_for :users, :controllers => { registrations: 'registrations' }
  authenticated :user do
    root to: 'vendors#index'
  end

  root to: "sessions#index"

  get '/super_admin_delete', to: 'users#super_admin_delete'

  get '/forum', to: 'posts#forum'
  get '/documents/:id/download', to: 'documents#download', as: :download

  resources :users

  resources :documents, only: [:new, :create, :index, :show, :destroy]

  resources :roles, only: [:new, :create]
  post '/admin', to: 'roles#admin'
  post '/member', to: 'roles#member'

  resources :posts, only: [:new, :create, :edit, :update, :destroy]

  resources :privacy, only: [:edit, :update]

  resources :organisations, only: [:new, :create, :edit, :update]

  resources :password_resets

  resources :vendors do
    resources :reviews, except: :index
    resources :offerings
  end

  # resources :reviews do
  #   resources :votes
  # end

  resources :categories, only: [:index, :show, :new, :create]

  get 'locations/all', to: 'locations#all'
  resources :locations, only: [:index, :show, :all, :new, :create, :edit, :update]

  namespace :admin do
    resources :vendors
    resources :users do
      resources :roles
    end
  end

  get '/data', to: 'categories#data'

end

app/views/shared/_forum_posts.html.erb
<% @posts.each do |post| %>

<div class="forum-post">
  <h2><%= post.title %></h2>

  <% if post.user %>
    <h5>posted by: <%= post.user.full_name %></h5>
  <% end %>

  <p><%= sanitize post.content.html_safe %></p>

  <% if post.user.id == current_user.id || current_user.email == "felipe@cpa.coop" %>
   <%= link_to "Edit post", edit_post_path(post) %>
   <%= link_to "Delete post", post_path(post), method: :delete %>
  <% end %>

</div>

<% end %>

app/views/shared/_list_reviews.html.erb
<% if @reviews.length > 0 %> <%# 1 %>
  <br>
	<div class = "reviews">
		<% @reviews.each do |review| %> <%# 2 %>

      <div class = "individual-review">

      <% if review.title %> <%# 3 %>
        <div id="name">
  		    <%= link_to review.title, vendor_review_path(review.vendor_id, review.id) %>
          <% if review.rating %> <%# 4 %>
            <span> | </span>
            <span class="star-rating" data-score=<%= review.rating %>></span>
      		  <br>
          <% end %> <%# 4 %>
        </div>



      <% if review.content && review.user %> <%# 5 %>
        <%= review.content %><br>
        (Added by <%= link_to review.user.full_name, user_path(review.user.id) %> on <%= review.created_at.strftime("%B %d, %Y") %>)<br>
      <% end %> <%# 5 %>


      <% end %> <%# 3 %>
      </div>
      <br>
      <br>

    <% end %> <%# 2 %>
	</div>
<% end %> <%# 1 %>

<script type="text/javascript">
  $('.star-rating').raty({
    path: '/assets/',
    readOnly: true,
    score: function() {
      return $(this).attr('data-score');
    }
  });
</script>

app/views/shared/_list_reviews_user_show.html.erb
<% if @reviews.length > 0 %> <%# 1 %>
  <br>
  <div class = "reviews">
    <% @reviews.each do |review| %> <%# 2 %>

      <div class = "individual-review">

      <% if review.title %> <%# 3 %>
        <div id="name">
          Review of <%=link_to review.vendor.name, vendor_path(review.vendor.id) %> titled <%= link_to review.title, vendor_review_path(review.vendor_id, review.id) %><br>
          <% if review.rating %> <%# 4 %>
            <span class="star-rating" data-score=<%= review.rating %>></span>
            <br>
          <% end %> <%# 4 %>
        </div>



      <% if review.content && review.user %> <%# 5 %>
        <%= review.content %><br>
        (Added by <%= link_to review.user.full_name, user_path(review.user.id) %> on <%= review.created_at.strftime("%B %d, %Y") %>)<br>
      <% end %> <%# 5 %>


      <% end %> <%# 3 %>
      </div>
      <br>
      <br>

    <% end %> <%# 2 %>
  </div>
<% end %> <%# 1 %>

<script type="text/javascript">
  $('.star-rating').raty({
    path: '/assets/',
    readOnly: true,
    score: function() {
      return $(this).attr('data-score');
    }
  });
</script>

app/views/shared/_list_single_inside_block.html.erb
      <% if review.title %>
        <div id="name">
  		    <h3>Review of <%= link_to review.vendor.name, vendor_path(review.vendor.id) %> titled <%= link_to review.title, vendor_review_path(review.vendor_id, review.id) %></h3>
        </div>
      <% end %>
                  
      <% if review.rating %>
        <div class="star-rating" data-score=<%= review.rating %>></div>
  		  <br>
      <% end %>
      
      <% if review.content %>
        <%= review.content %><br><br>
        (Written by <%= link_to review.user.full_name, user_path(review.user.id) %> on <%= review.created_at.strftime("%B %d, %Y") %>)<br><br>
      <% end %>

app/views/shared/_list_single_review.html.erb
      <% if @review.title %>
        <div id="name">
          <h3>Review of <%= link_to @review.vendor.name, vendor_path(@review.vendor.id) %> titled <%= link_to @review.title, vendor_review_path(@review.vendor_id, @review.id) %></h3>
        </div>

      <% if @review.rating %>
        <div class="star-rating" data-score=<%= @review.rating %>></div>
        <br>
      <% end %>

      <% end %>


      <% if @review.content %>
        <%= @review.content %><br><br>
        (Written by <%= link_to @review.user.full_name, user_path(@review.user.id) %> on <%= @review.created_at.strftime("%B %d, %Y") %>)<br><br>
      <% end %>

      <% if admin? && @review.user_id != current_user.id %>
        <p><%= link_to "Admin: Edit This Review", edit_vendor_review_path(@vendor, @review) %></p>
      <% end %>

      <% if @review.user_id == current_user.id %>
        <p><%= link_to "Edit My Review", edit_vendor_review_path(@vendor, @review) %></p>
      <% end %>

app/views/shared/_login.html.erb
<div class="alert">
	<p><%= flash[:notice] %></p>
	<p><%= flash[:alert] %></p>
</div>

<h2>Log in</h2>


<%# form_tag('/login', class: "form-group") do %>
	<%# image_tag('user.svg', class: "icon") %>
  <%# label_tag(:email, "Email (case sensitive!):") %>
  <%# text_field_tag(:email) %>
  <%# label_tag(:password, "Password:") %>
  <%# password_field_tag :password, nil, class: 'form-group password'%>
  <%# submit_tag("Login") %>
  <%# link_to "Forgot your password?", new_password_reset_path %>
<%# end %>