config/routes.rb
  Rails.application.routes.draw do

  # namespace :admin do
  #   resources :users
  #   root to: "devise/sessions#new"
  # end

  # root to: 'vendors#index'

  # devise_for :users
  # devise_scope :users do
  #   get '/', to: "devise/sessions#new"
  # end
  # root to: "sessions#index"


  devise_for :users, :controllers => { registrations: 'registrations' }
  authenticated :user do
    root to: 'vendors#index'
  end

  root to: "sessions#index"

  get '/super_admin_delete', to: 'users#super_admin_delete'

  get '/forum', to: 'posts#forum'
  get '/documents/:id/download', to: 'documents#download', as: :download

  resources :users

  resources :documents, only: [:new, :create, :index, :show, :destroy]

  resources :roles, only: [:new, :create]
  post '/admin', to: 'roles#admin'
  post '/member', to: 'roles#member'

  resources :posts, only: [:new, :create, :edit, :update, :destroy]

  resources :privacy, only: [:edit, :update]

  resources :organisations, only: [:new, :create, :edit, :update]

  resources :password_resets

  resources :vendors do
    resources :reviews, except: :index
    resources :offerings
  end

  # resources :reviews do
  #   resources :votes
  # end

  resources :categories, only: [:index, :show, :new, :create]

  get 'locations/all', to: 'locations#all'
  resources :locations, only: [:index, :show, :all, :new, :create, :edit, :update]

  namespace :admin do
    resources :vendors
    resources :users do
      resources :roles
    end
  end

  get '/data', to: 'categories#data'

end

app/models/document.rb
class Document < ApplicationRecord
	belongs_to :user
	mount_uploader :media, MediaUploader
end

app/controllers/admin/documents_controller.rb
class Admin::DocumentsController < ApplicationController

	def index
		if admin?
			@user = current_user
			@documents = Document.all
			
		else
      flash[:access] = "Unauthorized access, please contact an administrator if you believe this error is incorrect."
      redirect_to '/'
    end
	end
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController

  before_action :require_login

	# form to upload a new document
	def new
		if logged_in?
			@user = current_user
			@document = @user.documents.new
		else
			flash[:access] = "Unauthorized access, please contact an administrator if you believe this error is incorrect."
			redirect_to '/'
		end
	end

	# create action for new document
	def create
		@user = current_user
		@document = @user.documents.new(doc_params)
		if @user.save
			redirect_to documents_path
		else
			@errors = @user.errors.full_messages + @document.errors.full_messages
			render "new"
		end
	end

	# show all documents uploaded for one user
	def index
		@user = current_user
		if admin? 
			@documents = Document.all
		elsif logged_in?
			@documents = @user.documents
		else
      flash[:access] = "Unauthorized access, please contact an administrator if you believe this error is incorrect."
      redirect_to '/'
    end
	end

	# show one document (in full resolution if multiple sizes are used)
	def show
		@user = current_user
		doc = Document.find(params[:id])
		if admin? || (logged_in? && @user.documents.include?(doc))
			@document = doc
		else
			flash[:access] = "Unauthorized access, please contact an administrator if you believe this error is incorrect."
			redirect_to '/'
		end
	end

	def destroy
		@document = Document.find(params[:id])
		if admin? || (logged_in? && @document.user.id == current_user.id)
			@document.destroy
			redirect_to documents_path
		else
			flash[:access] = "Unauthorized access, please contact an administrator if you believe this error is incorrect."
			redirect_to '/'
		end
	end

	def download
		@document = Document.find(params[:id])
		if admin? || (logged_in? && @document.user.id == current_user.id)
	  	send_file(@document.media.path)
	  end
	end

	private 
	def doc_params
		params.require(:document).permit(:name, :media, :remote_media_url)
	end
end

app/views/documents/index.html.erb
<h1><%= @user.full_name %> documents</h1>

<div class="alert">
<% if @errors %>
	<% @errors.each do |error| %>
		<%= error %>
	<% end %>
<% end %>
</div>

<div id="images">
	<% @documents.each do |document| %>
		<% if document.media? %>
			<div class="image">
			<%= image_tag document.media_url(:small) if document.media? && image?(document.media) %>
				<div class="image_name">
					<%= document.name %>
				</div>
				<% if admin? %>
					<%= document.user.full_name %> - 
					<%= document.user.email %>
				<% end %>
				<div>
					<%= link_to "view document", document_path(document) %>
				</div>
			</div>
		<% end %>
	<% end %>
</div>

<%= link_to "Upload a new document", new_document_path %> | 
<%= link_to "Back to your profile", user_path(@user) %>

app/views/documents/new.html.erb
<div class="alert">
<% if @errors %>
	<% @errors.each do |error| %>
		<%= error %>
	<% end %>
<% end %>
</div>

<h1>Upload a document or image from your device</h1>

<%= form_for [@document], html: {class: "form-group", multipart: true } do |f| %>
	<%= f.label :name %>
	<%= f.text_field :name %>
	<%= f.file_field :media, accept: 'image/*, .pdf, .doc, .docx, .xls, .xlsx', capture: "camera" %>
	<%= f.label :remote_media_url, "or document URL" %>
	<%= f.text_field :remote_media_url %>
	<%= f.submit "Upload" %>
<% end %>

<%= link_to "Back to your documents", documents_path %> | 
<%= link_to "Back to your profile", user_path(@user) %>

app/views/documents/show.html.erb
<div class="image">
	<%= image_tag @document.media_url if @document.media? && image?(@document.media) %>
	<div class="image_name">
		<%= @document.name %>
	</div>
	<%= link_to "download", download_path(@document) %>
	<% if admin? || current_user.id == @document.user.id %>
		<%= link_to "delete", document_path(@document), method: :delete %>
	<% end %>
</div>

<%= link_to "Back to your documents", documents_path %> | 
<%= link_to "Back to your profile", user_path %>