config/routes.rb
  Rails.application.routes.draw do

  # namespace :admin do
  #   resources :users
  #   root to: "devise/sessions#new"
  # end

  # root to: 'vendors#index'

  # devise_for :users
  # devise_scope :users do
  #   get '/', to: "devise/sessions#new"
  # end
  # root to: "sessions#index"


  devise_for :users, :controllers => { registrations: 'registrations' }
  authenticated :user do
    root to: 'vendors#index'
  end

  root to: "sessions#index"

  get '/super_admin_delete', to: 'users#super_admin_delete'

  get '/forum', to: 'posts#forum'
  get '/documents/:id/download', to: 'documents#download', as: :download

  resources :users

  resources :documents, only: [:new, :create, :index, :show, :destroy]

  resources :roles, only: [:new, :create]
  post '/admin', to: 'roles#admin'
  post '/member', to: 'roles#member'

  resources :posts, only: [:new, :create, :edit, :update, :destroy]

  resources :privacy, only: [:edit, :update]

  resources :organisations, only: [:new, :create, :edit, :update]

  resources :password_resets

  resources :vendors do
    resources :reviews, except: :index
    resources :offerings
  end

  # resources :reviews do
  #   resources :votes
  # end

  resources :categories, only: [:index, :show, :new, :create]

  get 'locations/all', to: 'locations#all'
  resources :locations, only: [:index, :show, :all, :new, :create, :edit, :update]

  namespace :admin do
    resources :vendors
    resources :users do
      resources :roles
    end
  end

  get '/data', to: 'categories#data'

end

app/models/vendor.rb
class Vendor < ApplicationRecord
  has_many :offerings
  has_many :categories, through: :offerings
  has_many :reviews

  validates :name, uniqueness: true
  validates :name, presence: true

  def full_address
  	self.street_address + " " + self.city + " " + self.state + " " + self.zip_code.to_s
  end

  def avg_rating
    avg_rating = 0
    reviews_ratings_array = self.reviews.map { |r| r.rating }
    if self.reviews.count > 0
      avg_rating = self.reviews.map { |r| r.rating }.reduce(0, :+) / self.reviews.count.to_f
      avg_rating = avg_rating.round(1)
      avg_rating
    else
  	  "n/a"
    end
  end

  def associate_category(string_or_category)
    if string_or_category.class == Category
      category = string_or_category
    else
      category = Category.find_or_create_by name: string_or_category
    end
    if category
      Offering.create vendor_id: self.id, category_id: category.id
    end

  end
end

app/controllers/vendors_controller.rb
class VendorsController < ApplicationController

  #before_action :require_login
  before_action :authenticate_user!

  def index
    @user = current_user
    @vendors = Vendor.all
    @categories = Category.all.order('name ASC')
    @offerings = Offering.all
    @vendor = Vendor.new
    @vendor_hashes = []

    @vendors.each do |vendor|
      vendor_hash = {
        vendor_id: vendor.id,
        vendor_name: vendor.name,
        vendor_reviews_count: vendor.reviews.count,
        vendor_avg_rating: vendor.avg_rating
      }
      @vendor_hashes << vendor_hash
    end

    @data = {
      vendors: @vendors,
      categories: @categories,
      offerings: @offerings,
      vendor_hashes: @vendor_hashes
    }
  end

  def show
    @vendor = Vendor.find(params[:id])
    @reviews = @vendor.reviews
    @vote = Vote.new
    @offering = Offering.new
    @categories = Category.all
  end

  def new
    @vendor = Vendor.new
    @vendors = Vendor.all
  end

  def create
    @vendor = Vendor.new(vendor_params)

    if @vendor.save
      redirect_to "/vendors/"+@vendor.id.to_s+"/offerings/new"
    else
      render 'index'
    end
  end

  def edit
    @vendor = Vendor.find(params[:id])
  end

  def update
    @vendor = Vendor.find(params[:id])

    if @vendor.update(vendor_params)
      redirect_to @vendor
    else
      render 'edit'
    end
  end

  private
  def vendor_params
    params.require(:vendor).permit(:name, :street_address, :city, :state, :zip_code, :phone, :email, :website)
  end

end

app/views/vendors/edit.html.erb
<center>
  <h1>Update <%=@vendor.name%>'s Information</h1>
</center>
<%= form_for @vendor, html: {class: "form-group"} do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %><br>
  <%= f.label :street_address %>
  <%= f.text_field :street_address %><br>
  <%= f.label :city %>
  <%= f.text_field :city %><br>
  <%= f.label :state %>
  <%= f.text_field :state %><br>
  <%= f.label :zip_code %>
  <%= f.text_field :zip_code %><br>
  <%= f.label :phone %>
  <%= f.text_field :phone %><br>
  <%= f.label :email %>
  <%= f.text_field :email %><br>
  <%= f.label :website %>
  <%= f.text_field :website %><br>

  <%= f.submit "Submit Vendor" %> 
<% end %>

app/views/vendors/index.html.erb
<%= react_component 'AllCategories', {data: @data} %>


<center>
<br>
  <h4>Can't find the Vendor you are looking for? <%= link_to 'Add it now!', new_vendor_path %> </h4>
</center>

app/views/vendors/new.html.erb
<%= react_component 'NewVendorForm', {data: @vendors}, authenticity_token: form_authenticity_token %>

app/views/vendors/show.html.erb
<div id="page-top">
<div id="vendor-information">
  <h1><%= @vendor.name %> </h1>
 <div class='star-container'>
  <div class="right-container">
    <div class="right-decorator-show">
      <%= react_component 'BigStar', {rating: @vendor.avg_rating, style: 'show'} %>
    </div>
  </div>
 </div>

  <br>

  <div id="review-link"><%=image_tag("outline-star.png")%><%= link_to "Write a Review", new_vendor_review_path(@vendor) %></div><br><br>

  <h4>
    <% if @vendor.street_address %>
      <%= @vendor.street_address %>,<br>
      <%= @vendor.city %>, <%= @vendor.state %>, <%= @vendor.zip_code %>
    <% end %>
  </h4>

  <% if @vendor.phone != nil && @vendor.phone.length > 0 %>
    <h4>Phone: <%= @vendor.phone %></h4>
  <% end %>
  <% if @vendor.email != nil && @vendor.email.length >0 %>
    <h4>Email: <%= @vendor.email%></h4>
  <% end %>
  <% if @vendor.website != nil && @vendor.website.length > 0 %>
    <h4>Website: <%= @vendor.website%></h4>
  <% end %>

<%# if admin? %>
  <%= link_to "Update Vendor Information", edit_vendor_path(@vendor) %><br><br>
<%# end %>

  <br><br>
</div>

<div class="left">

  <% if @vendor.categories.count > 0 %>
    <h3><%= @vendor.name %> does work in:</h3>
    <ul>
      <% @vendor.categories.each do |category| %>
        <li><%= category.name %></li>
      <% end %>
    </ul>
  <% end %>

<%= link_to "Add to this list of services", new_vendor_offering_path(@vendor) %>

</div>
</div>


<%= render "shared/list_reviews", locals: { reviews: @reviews, vote: @vote} %>

<script type="text/javascript">
  $('.star-rating').raty({
    path: '/assets/',
    readOnly: true,
    score: function() {
      return $(this).attr('data-score');
    }
  });
</script>